baseURL = 'https://passivepacket.github.io/'
languageCode = 'en-us'
title = 'PassivePacket'
theme = 'PaperMod'

[params]
  author = 'PassivePacket'
  defaultTheme = 'dark'
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
